// program prog 
// Generated by Structorizer 3.26-05 

int main(void)
{
	// TODO: Check and accomplish variable declarations: 
	int i;
	
	int i;
	for (i = 0; i <= 10; i += (1))
	{
		writeln "Hello";
	}
	
	return 0;
}